



 let cameraSuggestions=[
    "GoPro Hero 9 Sports & Action Camera",
    "Canon XA11 Camcorder",
    "Canon HF R72 Camcorder",
    "Samsung HMX-F90 Camcorder",
    "Samsung SC-MX20 Camcorder",
    "Nikon Z50 (Body) Mirrorless Camera",
    "Nikon Z6 (Body) Mirrorless Camera",
    "Polaroid ID610 Camcorder",
    "Panasonic Lumix HC-PV100 Camcorder",
    "Sony NXCAM HXR-NX100 Camcorder",
    "Sony XDCAM PXW-Z90 Camcorder",
    "Olympus SP-590UZ Bridge Camera",
    "Olympus SP-620UZ Bridge Camera",
    "Zeiss ZX1 Point & Shoot Camera",
    "Fujifilm FinePix S1000fd Bridge Camera",
    "Fujifilm FinePix S8650 Bridge Camera",
    "Fujifilm FinePix S2950 Bridge Camera",
    "Panasonic Lumix HC-PV100 Camcorder",
    "Sony XDCAM PXW-X70 Camcorder",
    "Canon EOS 2000D (Body) Digital SLR Camera",

 ];

 let laptopSuggestions=[
    "HP Pavillion",
    "Avita Pura",
    "Acer Aspire 7",
    "Lenovo Ideapad Slim 3i",
    "MSI GF63 Thin",
    "Apple Macbook Air",
    "Lenovo Ideapad Gaming",
    "Dell Inspiron",
    "Asus TUF Gaming F15",
    "Asus ROG",
    "Lenovo Ideapad 3",
    "Dell G15",
    "HP 14S",
    "Apple Macbook Air",
    "Acer Aspire 5",
    "Avita Liber",
    "MSI Modern 15",
    "HP Pavillion Aero",
    "Asus Vivobook 15",
    "Dell Vostro",
 ];

 let mobileSuggestions=[
    "Samsung F42 5G",
    "Reliance Jio phone 3",
    "Poco M3 Pro 5G",
    "Redmi Note 9 Pro Max",
    "SamsungA21s",
    "Vivo bX70 Pro",
    "Redmi Note 10 Pro",
    "Realme 8 Pro",
    "Samsung Galaxy M51",
    "Oneplus8 Pro",
    "Realme 8i",
    "Poco X3 Pro",
    "Samsung M52 5G",
    "Nokia Play 2 Max",
    "Xiomi Redmi Note 8",
    "Poco X3 ",
    "Apple iPhone 13 Pro",
    "Oppo Reno 6",
    "Vivo V21",
 ];

let powerbankSuggestions=[
    "MI 3i",
    "URBN a1",
    "Ambrane p6",
    "Syska a4911",
    "Oneplus 2a",
    "pTron Dyanamo Pro",
    "Realme X1",
    "Redmi 4i",
    "Anker 6T",
    "Croma 10i",
 ];

 let refirgiratorSuggestions=[
    "Samsung",
    "Whirlpool",
    "LG",
    "Bosch",
    "Haier",
    "Electrolux",
    "Panasonic",
    "Kelvinator",
    "Godrej",
    "Hitachi",
    "Blue Star",
    "Voltas",
    "Sansui",
    "Koryo",
    "Croma",
    "Intex",
    "Dolphy",
    "Superstar",
    "Mi",
 ];

 let smartwatchSuggestions=[
    "Xiaomi Mi Watch",
    "Xiaomi Mi Watch Evolve",
    "Boat Xtend",
    "boAt Watch Enigma Smartwatch",
    "Apple Watch Series 4",
    "Apple Watch Series 6",
    "Apple Watch Series 5",
    "Noise Urge",
    "Noise Edge",
    "Noise Turbo",
    "Noise Colorfit Pro 2",
    "Xiaomi Mi Watch Lite",
    "Fossil Gen 5",
    "Fossil Q Activist Hybrid",
    "Samsung Galaxy Watch 4",
    "Samsung Gear S3 Frontier",
    "Huawei Watch Fit",
    "Huawei Watch GT 2e",
    "Garmin Pilot",
    "Garmin Venu",
 ];

 let tabletSuggestions=[
    "Honor Tablet X7",
    "Huawei Enjoy Tablet 2 Wi-Fi",
    "Lenovo Yoga Tab 11",
    "Samsung Galaxy Tab A 8.0 2019",
    "Samsung Galaxy Tab S6 Lite",
    "Xiaomi Mi Pad 5",
    "Lenovo Tab M8 (2GB, 32GB, WiFi",
    "FUSION5 Yoga Tab 11",
    "Apple MUQW2HN/A",
    "Apple iPad mini",
    "Lenovo Tab M7 3rd Gen",
    "Lenovo M10 FHD Plus (2nd Gen)",
    "Panasonic Tab 8 HD",
    "IKALL N5",
    "IKALL N13",
    "Samsung Galaxy Tab A7 Lite",
    "Samsung Galaxy Tab S6 LTE",
    "Samsung Galaxy Tab S7 FE",
    "Lenovo Tab P11",
    "Lenovo Tab K10 FHD",
 ];

 let televisionSuggestions=[
    "Samsung UA32T4340AK",
    "RealMe Smart TV 32",
    "Xiaomi Mi TV 4A",
    "LG 32LM565BPTA",
    "Xiaomi Mi TV 4A Pro",
    "Sony BRAVIA KDL-32W6103",
    "Xiaomi Mi TV 4A Pro",
    "Noble Skiodo BLT39OD01",
    "Sony BRAVIA KD-55X80J 55",
    "OnePlus 32Y1",
    "OnePlus 43Y1",
    "LG 32LM560BPTC",
    "Xiaomi Mi TV 4X",
    "Xiaomi Mi TV 4X",
    "Xiaomi Mi TV 4X",
    "OnePlus 40Y1",
    "LG 43M565PTA",
    "Sony BRAVIA KDL-32W6100",
    "Sony KDL-43W6603",
    "Thompson 32PATH001",
 ];

 let washingmachineSuggestions=[
    "IFB Senator",
    "LG FHT1408ZWL",
    "LG T65SNSF1Z",
    "Bosch WAJ2846SIN",
    "LG FHV1409ZWB",
    "Whirlpool Whitemagic",
    "Samsung WW80T504DAN",
    "Godrej WT EON",
    "Panasonic NAF72LR8CRB",
    "BPL BFATL72N1",
    "Electrolux ET65SATB",
    "Lloyd Kid O Matic",
    "Whirlpool Supreme Care",
    "Voltas Beko WFL60SS",
    "Videocon VT55H12",
    "Intex",
    "Amstrad AMWF70Di",
    "Sansui JSX90FFL-2022C",
    "Lloyd Stalwart"
];